- name: my play with conditions
  hosts: all
  tasks:
  - name: my task1 with conditions
    apt:
      name: nginx
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: my task2 with conditions
    apt:
      name: httpd
    when: ansible_facts['distribution'] == "CentOS"